{{- if .Values.executor.enabled -}}
apiVersion: v1
data:
  daemon.json: |
    { "insecure-registries":["private-docker-registry:5000"] }

kind: ConfigMap
metadata:
  labels:
    app: executor
    deploy: sourcegraph
    app.kubernetes.io/component: executor
  name: docker-config
{{- end }}