apiVersion: v2
name: sourcegraph-executor
description: Chart for installing Sourcegraph executors
icon: https://sourcegraph.com/favicon.ico
type: application

# Chart version, separate from Sourcegraph
version: "5.0.1"

# Version of Sourcegraph release
appVersion: "5.0.1"
