{{- if and .Values.sourcegraph.createKubernetesSecrets (not .Values.pgsql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgsql.name }}-auth
  labels:
    app: pgsql
    deploy: sourcegraph
    app.kubernetes.io/component: pgsql
type: Opaque
data:
  database: {{ .Values.pgsql.auth.database | toString | b64enc | quote }}
  host: {{ .Values.pgsql.auth.host | toString | b64enc | quote }}
  password: {{ .Values.pgsql.auth.password | toString | b64enc | quote }}
  port: {{ .Values.pgsql.auth.port | toString | b64enc | quote }}
  user: {{ .Values.pgsql.auth.user | toString | b64enc | quote }}
  sslmode: {{ .Values.pgsql.auth.sslmode | toString | b64enc | quote }}
{{- end -}}
