{{- if .Values.pgsql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.pgsql.serviceAnnotations }}
    {{- toYaml .Values.pgsql.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: pgsql
    deploy: sourcegraph
    app.kubernetes.io/component: pgsql
    {{- if .Values.pgsql.serviceLabels }}
      {{- toYaml .Values.pgsql.serviceLabels | nindent 4 }}
    {{- end }}
  name: pgsql
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: pgsql
  type: {{ .Values.pgsql.serviceType | default "ClusterIP" }}
{{- end }}
