{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.grafana.serviceAnnotations }}
  annotations:
  {{- toYaml .Values.grafana.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "grafana") | nindent 4 }}
  name: grafana
spec:
  ports:
  - name: http
    port: 30070
    targetPort: http
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "grafana") | nindent 4 }}
  type: {{ .Values.grafana.serviceType | default "ClusterIP" }}
{{- end }}
