{{- if .Values.codeInsightsDB.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeInsightsDB" "kind" "persistentvolumeclaim" "componentLabel" "codeinsights-db") | nindent 4 }}
  name: {{ default "codeinsights-db" .Values.codeIntelDB.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.codeInsightsDB.storageSize }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- if .Values.codeInsightsDB.volumeName }}
  volumeName: {{ .Values.codeInsightsDB.volumeName }}
  {{- end }}
{{- end }}
