{{- if .Values.codeInsightsDB.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.codeInsightsDB.serviceAnnotations }}
    {{- toYaml .Values.codeInsightsDB.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeInsightsDB" "kind" "service" "componentLabel" "codeinsights-db") | nindent 4 }}
  name: codeinsights-db
spec:
  ports:
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  - name: codeinsights-db
    port: 5432
    targetPort: codeinsights-db
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "codeInsightsDB" "componentLabel" "codeinsights-db") | nindent 4 }}
  type: {{ .Values.codeInsightsDB.serviceType | default "ClusterIP" }}
{{- end }}
