{{- if and .Values.codeInsightsDB.enabled .Values.codeInsightsDB.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeInsightsDB" "kind" "serviceaccount" "componentLabel" "codeinsights-db") | nindent 4 }}
  {{- include "sourcegraph.serviceAccountAnnotations" (list . "codeInsightsDB") | trim | nindent 2 }}
  name: {{ include "sourcegraph.serviceAccountName" (list . "codeInsightsDB") }}
{{- end }}
