{{- if and .Values.sourcegraph.createKubernetesSecrets (not .Values.codeInsightsDB.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.codeInsightsDB.name }}-auth
  labels:
    app: codeinsights-db
    deploy: sourcegraph
    app.kubernetes.io/component: codeinsights-db
type: Opaque
data:
  database: {{ .Values.codeInsightsDB.auth.database | toString | b64enc | quote }}
  host: {{ .Values.codeInsightsDB.auth.host | toString | b64enc | quote }}
  password: {{ .Values.codeInsightsDB.auth.password | toString | b64enc | quote }}
  port: {{ .Values.codeInsightsDB.auth.port | toString | b64enc | quote }}
  user: {{ .Values.codeInsightsDB.auth.user | toString | b64enc | quote }}
  sslmode: {{ .Values.codeInsightsDB.auth.sslmode | toString | b64enc | quote }}
{{- end -}}
