apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Rate-limiting proxy for the GitHub API.
    kubectl.kubernetes.io/default-container: github-proxy
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    {{- if .Values.githubProxy.labels }}
      {{- toYaml .Values.githubProxy.labels | nindent 4 }}
    {{- end }}
    deploy: sourcegraph
    app.kubernetes.io/component: github-proxy
  name: {{ default "github-proxy" .Values.githubProxy.name }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.githubProxy.replicaCount }}
  revisionHistoryLimit: {{ .Values.sourcegraph.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: github-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
      {{- if .Values.sourcegraph.podAnnotations }}
      {{- toYaml .Values.sourcegraph.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.githubProxy.podAnnotations }}
      {{- toYaml .Values.githubProxy.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "sourcegraph.selectorLabels" . | nindent 8 }}
      {{- if .Values.sourcegraph.podLabels }}
      {{- toYaml .Values.sourcegraph.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.githubProxy.podLabels }}
      {{- toYaml .Values.githubProxy.podLabels | nindent 8 }}
      {{- end }}
        app: github-proxy
        deploy: sourcegraph
    spec:
      containers:
      - name: github-proxy
        image: {{ include "sourcegraph.image" (list . "githubProxy") }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        {{- range $name, $item := .Values.githubProxy.env}}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 3180
          name: http
        {{- if not .Values.sourcegraph.localDevMode }}
        resources:
          {{- toYaml .Values.githubProxy.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.githubProxy.podSecurityContext | nindent 10 }}
        volumeMounts:
        {{- if .Values.githubProxy.extraVolumeMounts }}
        {{- toYaml .Values.githubProxy.extraVolumeMounts | nindent 8 }}
        {{- end }}
      {{- include "sourcegraph.tracing" . | nindent 6 }}
      {{- if .Values.githubProxy.extraContainers }}
        {{- toYaml .Values.githubProxy.extraContainers | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.githubProxy.securityContext | nindent 8 }}
      {{- include "sourcegraph.nodeSelector" (list . "githubProxy" ) | trim | nindent 6 }}
      {{- include "sourcegraph.affinity" (list . "githubProxy" ) | trim | nindent 6 }}
      {{- include "sourcegraph.tolerations" (list . "githubProxy" ) | trim | nindent 6 }}
      {{- with .Values.sourcegraph.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.githubProxy.extraVolumes }}
      {{- toYaml .Values.githubProxy.extraVolumes | nindent 6 }}
      {{- end }}
