{{- if .Values.cadvisor.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    description: DaemonSet to ensure all nodes run a cAdvisor pod.
    seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    {{- if .Values.cadvisor.labels }}
      {{- toYaml .Values.cadvisor.labels | nindent 4 }}
    {{- end }}
    deploy: sourcegraph
    app.kubernetes.io/component: cadvisor
  name: {{ .Values.cadvisor.name }}
spec:
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: cadvisor
  template:
    metadata:
      annotations:
        description: Collects and exports container metrics.
        kubectl.kubernetes.io/default-container: cadvisor
        prometheus.io/port: "48080"
        sourcegraph.prometheus/scrape: "true"
      {{- if .Values.sourcegraph.podAnnotations }}
      {{- toYaml .Values.sourcegraph.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.cadvisor.podAnnotations }}
      {{- toYaml .Values.cadvisor.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "sourcegraph.selectorLabels" . | nindent 8 }}
      {{- if .Values.sourcegraph.podLabels }}
      {{- toYaml .Values.sourcegraph.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.cadvisor.podLabels }}
      {{- toYaml .Values.cadvisor.podLabels | nindent 8 }}
      {{- end }}
        deploy: sourcegraph
        app: cadvisor
    spec:
      {{- include "sourcegraph.renderServiceAccountName" (list . "cadvisor") | trim | nindent 6 }}
      containers:
      - name: cadvisor
        image: {{ include "sourcegraph.image" (list . "cadvisor" ) }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        args:
        # Kubernetes-specific flags below (other flags are baked into the Docker image)
        #
        # disable container labels to allow whitelisting to reduce noise
        - --store_container_labels=false
        - --whitelisted_container_labels=io.kubernetes.container.name,io.kubernetes.pod.name,io.kubernetes.pod.namespace,io.kubernetes.pod.uid
        # it is safe to uncomment this option if you use docker as your container runtime to reduce noise
        # - --docker_only
        env:
        {{- range $name, $item := .Values.cadvisor.env}}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        {{- if not .Values.sourcegraph.localDevMode }}
        resources:
          {{- toYaml .Values.cadvisor.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.cadvisor.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
        {{- if .Values.cadvisor.containerSecurityContext.privileged }}
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        {{- end }}
        {{- if .Values.cadvisor.extraVolumeMounts }}
        {{- toYaml .Values.cadvisor.extraVolumeMounts | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 48080
          protocol: TCP
      {{- if .Values.cadvisor.extraContainers }}
        {{- toYaml .Values.cadvisor.extraContainers | nindent 6 }}
      {{- end }}
      automountServiceAccountToken: false
      {{- if or .Values.cadvisor.priorityClassName .Values.sourcegraph.priorityClassName }}
      priorityClassName: {{ coalesce .Values.cadvisor.priorityClassName .Values.sourcegraph.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: 30
      securityContext:
        {{- toYaml .Values.cadvisor.podSecurityContext | nindent 8 }}
      {{- include "sourcegraph.nodeSelector" (list . "cadvisor" ) | trim | nindent 6 }}
      {{- include "sourcegraph.affinity" (list . "cadvisor" ) | trim | nindent 6 }}
      {{- include "sourcegraph.tolerations" (list . "cadvisor" ) | trim | nindent 6 }}
      {{- with .Values.sourcegraph.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: disk
        hostPath:
          path: /dev/disk
      {{- if .Values.cadvisor.containerSecurityContext.privileged }}
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      {{- end }}
      {{- if .Values.cadvisor.extraVolumes }}
      {{- toYaml .Values.cadvisor.extraVolumes | nindent 6 }}
      {{- end }}
{{- end }}
