{{- if and .Values.cadvisor.enabled .Values.cadvisor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- include "sourcegraph.serviceAccountAnnotations" (list . "cadvisor") | trim | nindent 2 }}
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "cadvisor" "kind" "serviceaccount") | nindent 4 }}
  name: {{ include "sourcegraph.serviceAccountName" (list . "cadvisor") }}
{{- end }}
