{{- if .Values.frontend.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- if .Values.frontend.ingress.annotations}}
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
    {{- end }}
  labels:
    app: sourcegraph-frontend
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
    {{- if .Values.frontend.ingress.labels}}
      {{- toYaml .Values.frontend.ingress.labels | nindent 4 }}
    {{- end }}
  name: sourcegraph-frontend
spec:
  {{- if and .Values.frontend.ingress.host .Values.frontend.ingress.tlsSecret }}
  tls:
  - hosts:
    - {{ .Values.frontend.ingress.host }}
    secretName: {{ .Values.frontend.ingress.tlsSecret }}
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sourcegraph-frontend
            port:
              number: 30080
  {{- if .Values.frontend.ingress.host}}
    host: {{ .Values.frontend.ingress.host }}
  {{- end }}
  {{- if .Values.frontend.ingress.ingressClassName}}
  ingressClassName: {{ .Values.frontend.ingress.ingressClassName }}
  {{- end }}
{{- end }}
