apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Serves the frontend of Sourcegraph via HTTP(S).
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    {{- if .Values.frontend.labels }}
      {{- toYaml .Values.frontend.labels | nindent 4 }}
    {{- end }}
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
  name: {{ .Values.frontend.name }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.frontend.replicaCount }}
  revisionHistoryLimit: {{ .Values.sourcegraph.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: sourcegraph-frontend
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: frontend
        {{- include "sourcegraph.authChecksum" . | nindent 8 }}
        {{- include "sourcegraph.redisChecksum" . | nindent 8 }}
      {{- if .Values.sourcegraph.podAnnotations }}
      {{- toYaml .Values.sourcegraph.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podAnnotations }}
      {{- toYaml .Values.frontend.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "sourcegraph.selectorLabels" . | nindent 8 }}
      {{- if .Values.sourcegraph.podLabels }}
      {{- toYaml .Values.sourcegraph.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.frontend.podLabels }}
      {{- toYaml .Values.frontend.podLabels | nindent 8 }}
      {{- end }}
        app: sourcegraph-frontend
        deploy: sourcegraph
    spec:
      initContainers:
      {{- if .Values.migrator.enabled }}
      - name: migrator
        image: {{ include "sourcegraph.image" (list . "migrator") }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        {{- if .Values.migrator.command }}
        command: {{ .Values.migrator.command }}
        {{- end }}
        args: {{- default (list "up") .Values.migrator.args | toYaml | nindent 8 }}
        env:
        {{- if and (not .Values.migrator.databaseAuthOverrideEnvVars) (not .Values.sourcegraph.disableKubernetesSecrets) }}
        {{- include "sourcegraph.databaseAuth" (list . "pgsql" "PG") | nindent 8 }}
        {{- include "sourcegraph.databaseAuth" (list . "codeIntelDB" "CODEINTEL_PG") | nindent 8 }}
        {{- include "sourcegraph.databaseAuth" (list . "codeInsightsDB" "CODEINSIGHTS_PG") | nindent 8 }}
        {{- end }}
        {{- range $name, $item := .Values.migrator.env }}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        {{- if not .Values.sourcegraph.localDevMode}}
        resources:
          {{- toYaml .Values.migrator.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.migrator.containerSecurityContext | nindent 10 }}
        volumeMounts:
        {{- if .Values.migrator.extraVolumeMounts }}
        {{- toYaml .Values.migrator.extraVolumeMounts | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
      - name: frontend
        image: {{ include "sourcegraph.image" (list . "frontend") }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        {{- if .Values.frontend.command }}
        command: {{ .Values.frontend.command }}
        {{- end }}
        args: {{- default (list "serve") .Values.frontend.args | toYaml | nindent 8 }}
        env:
        {{- if not .Values.sourcegraph.disableKubernetesSecrets }}
        {{- include "sourcegraph.databaseAuth" (list . "pgsql" "PG") | nindent 8 }}
        {{- include "sourcegraph.databaseAuth" (list . "codeIntelDB" "CODEINTEL_PG") | nindent 8 }}
        {{- include "sourcegraph.databaseAuth" (list . "codeInsightsDB" "CODEINSIGHTS_PG") | nindent 8 }}
        {{- end }}
        {{- range $name, $item := .Values.frontend.env}}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        {{- with include "sourcegraph.redisConnection" . | trim }}{{ . | nindent 8 }}{{- end }}
        {{- include "sourcegraph.openTelemetryEnv" . | nindent 8 }}
        {{- if .Values.blobstore.enabled }}
        - name: PRECISE_CODE_INTEL_UPLOAD_BACKEND
          value: blobstore
        - name: PRECISE_CODE_INTEL_UPLOAD_AWS_ENDPOINT
          value: http://blobstore:9000
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-debug
            scheme: HTTP
          initialDelaySeconds: 300
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: http-debug
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        ports:
        - name: grpc-internal
          containerPort: 3090
        - name: http
          containerPort: 3080
        - name: http-debug
          containerPort: 6060
        {{- if not .Values.sourcegraph.localDevMode }}
        resources:
          {{- toYaml .Values.frontend.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.frontend.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /home/sourcegraph
          name: home-dir
        {{- if .Values.frontend.extraVolumeMounts }}
        {{- toYaml .Values.frontend.extraVolumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.frontend.extraContainers }}
        {{- toYaml .Values.frontend.extraContainers | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.frontend.podSecurityContext | nindent 8 }}
      {{- include "sourcegraph.nodeSelector" (list . "frontend" ) | trim | nindent 6 }}
      {{- include "sourcegraph.affinity" (list . "frontend" ) | trim | nindent 6 }}
      {{- include "sourcegraph.tolerations" (list . "frontend" ) | trim | nindent 6 }}
      {{- with .Values.sourcegraph.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "sourcegraph.renderServiceAccountName" (list . "frontend") | trim | nindent 6 }}
      volumes:
      - name: home-dir
        emptyDir: {}
      {{- if .Values.frontend.extraVolumes }}
      {{- toYaml .Values.frontend.extraVolumes | nindent 6 }}
      {{- end }}
