apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.frontend.serviceAnnotations }}
    {{- toYaml .Values.frontend.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: sourcegraph-frontend
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
    {{- if .Values.frontend.serviceLabels }}
      {{- toYaml .Values.frontend.serviceLabels | nindent 4 }}
    {{- end }}
  name: sourcegraph-frontend
spec:
  ports:
  - name: http
    port: 30080
    targetPort: http
  - name: http-debug
    port: 6060
    targetPort: http-debug
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: sourcegraph-frontend
  type: {{ .Values.frontend.serviceType | default "ClusterIP" }}
