{{- if .Values.frontend.privileged -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "frontend" "kind" "role") | nindent 4 }}
  name: {{ .Values.frontend.name }}
rules:
- apiGroups:
  - ""
  resources:
  # necessary for resolving k8s+http://fooservice URLs (see for example searcher URL)
  - endpoints
  - endpointSlices
  # necessary to populate Site Admin/Instrumentation page (/-/debug) in the cluster deployment
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "apps"
  resources:
    # necessary for resolving k8s+http://indexed-search?kind=sts URLs
    - statefulsets
  verbs:
    - get
    - list
    - watch
{{- end }}
