apiVersion: v1
kind: Service
metadata:
  {{- if .Values.frontend.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.frontend.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
    app: sourcegraph-frontend
    deploy: sourcegraph
    app.kubernetes.io/component: frontend
    {{- if .Values.frontend.serviceLabels }}
      {{- toYaml .Values.frontend.serviceLabels | nindent 4 }}
    {{- end }}
  name: sourcegraph-frontend-internal
spec:
  ports:
  - name: grpc-internal
    port: 80
    targetPort: grpc-internal
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: sourcegraph-frontend
  type: {{ .Values.frontend.internalServiceType | default "ClusterIP" }}
