{{- if .Values.searcher.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "searcher" "kind" "serviceaccount") | nindent 4 }}
  {{- include "sourcegraph.serviceAccountAnnotations" (list . "searcher") | trim | nindent 2 }}
  name: {{ include "sourcegraph.serviceAccountName" (list . "searcher") }}
{{- end }}
