apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Backend for text search operations.
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    {{- if .Values.searcher.labels }}
      {{- toYaml .Values.searcher.labels | nindent 4 }}
    {{- end }}
    deploy: sourcegraph
    app.kubernetes.io/component: searcher
  name: {{ .Values.searcher.name }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.searcher.replicaCount }}
  revisionHistoryLimit: {{ .Values.sourcegraph.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: searcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: searcher
      {{- include "sourcegraph.redisChecksum" . | nindent 8 }}
      {{- if .Values.sourcegraph.podAnnotations }}
      {{- toYaml .Values.sourcegraph.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.searcher.podAnnotations }}
      {{- toYaml .Values.searcher.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "sourcegraph.selectorLabels" . | nindent 8 }}
      {{- if .Values.sourcegraph.podLabels }}
      {{- toYaml .Values.sourcegraph.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.searcher.podLabels }}
      {{- toYaml .Values.searcher.podLabels | nindent 8 }}
      {{- end }}
        deploy: sourcegraph
        app: searcher
    spec:
      containers:
      - name: searcher
        {{- with .Values.searcher.args }}
        args:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        {{- include "sourcegraph.redisConnection" .| nindent 8 }}
        {{- range $name, $item := .Values.searcher.env}}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        - name: SEARCHER_CACHE_SIZE_MB
          valueFrom:
            resourceFieldRef:
              containerName: searcher
              resource: requests.ephemeral-storage
              divisor: 1M
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CACHE_DIR
          value: /mnt/cache/$(POD_NAME)
        {{- if .Values.otelCollector.enabled }}
        # OTEL_AGENT_HOST must be defined before OTEL_EXPORTER_OTLP_ENDPOINT to substitute the node IP on which the DaemonSet pod instance runs in the latter variable
        - name: OTEL_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_AGENT_HOST):4317
        {{- end }}
        image: {{ include "sourcegraph.image" (list . "searcher" ) }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 3181
          name: http
        - containerPort: 6060
          name: debug
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /mnt/cache
          name: cache-ssd
        - mountPath: /tmp
          name: tmpdir
        {{- if .Values.searcher.extraVolumeMounts }}
        {{- toYaml .Values.searcher.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if not .Values.sourcegraph.localDevMode }}
        resources:
          {{- toYaml .Values.searcher.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.searcher.containerSecurityContext | nindent 10 }}
      {{- if .Values.searcher.extraContainers }}
        {{- toYaml .Values.searcher.extraContainers | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.searcher.podSecurityContext | nindent 8 }}
      {{- include "sourcegraph.nodeSelector" (list . "searcher" ) | trim | nindent 6 }}
      {{- include "sourcegraph.affinity" (list . "searcher" ) | trim | nindent 6 }}
      {{- include "sourcegraph.tolerations" (list . "searcher" ) | trim | nindent 6 }}
      {{- with .Values.sourcegraph.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "sourcegraph.renderServiceAccountName" (list . "searcher") | trim | nindent 6 }}
      volumes:
      - emptyDir: {}
        name: cache-ssd
      - emptyDir: {}
        name: tmpdir
      {{- if .Values.searcher.extraVolumes }}
      {{- toYaml .Values.searcher.extraVolumes | nindent 6 }}
      {{- end }}
