{{- if .Values.minio.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: MinIO for storing LSIF uploads.
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    {{- if .Values.minio.labels }}
      {{- toYaml .Values.minio.labels | nindent 4 }}
    {{- end }}
    deploy: sourcegraph
    app.kubernetes.io/component: minio
  name: {{ default "minio" .Values.minio.name }}
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: {{ .Values.sourcegraph.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: minio
        checksum/minio.secret: {{ include (print $.Template.BasePath "/minio/minio.Secret.yaml") . | sha256sum }}
      {{- if .Values.sourcegraph.podAnnotations }}
      {{- toYaml .Values.sourcegraph.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.minio.podAnnotations }}
      {{- toYaml .Values.minio.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "sourcegraph.selectorLabels" . | nindent 8 }}
      {{- if .Values.sourcegraph.podLabels }}
      {{- toYaml .Values.sourcegraph.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.minio.podLabels }}
      {{- toYaml .Values.minio.podLabels | nindent 8 }}
      {{- end }}
        deploy: sourcegraph
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: {{ default "minio-auth" .Values.minio.auth.existingSecret }}
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ default "minio-auth" .Values.minio.auth.existingSecret }}
        {{- range $name, $item := .Values.minio.env}}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        image: {{ include "sourcegraph.image" (list . "minio") }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        args: {{- default (list "minio" "server" "/data") .Values.minio.args | toYaml | nindent 8 }}
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 9000
          name: minio
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: minio
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /minio/health/live
            port: minio
            scheme: HTTP
          periodSeconds: 5
          timeoutSeconds: 5
        {{- if not .Values.sourcegraph.localDevMode }}
        resources:
          {{- toYaml .Values.minio.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.minio.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: minio-data
          mountPath: /data
        - name: minio
          mountPath: /minio
        {{- if .Values.minio.extraVolumeMounts }}
        {{- toYaml .Values.minio.extraVolumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.minio.extraContainers }}
        {{- toYaml .Values.minio.extraContainers | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.minio.podSecurityContext | nindent 8 }}
      {{- include "sourcegraph.nodeSelector" (list . "minio" ) | trim | nindent 6 }}
      {{- include "sourcegraph.affinity" (list . "minio" ) | trim | nindent 6 }}
      {{- include "sourcegraph.tolerations" (list . "minio" ) | trim | nindent 6 }}
      {{- with .Values.sourcegraph.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "sourcegraph.renderServiceAccountName" (list . "minio") | trim | nindent 6 }}
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio
      - name: minio
        emptyDir: {}
      {{- if .Values.minio.extraVolumes }}
      {{- toYaml .Values.minio.extraVolumes | nindent 6 }}
      {{- end }}
{{- end }}
