{{- if .Values.minio.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: minio
  name: {{ default "minio" .Values.minio.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storageSize }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- if .Values.minio.volumeName }}
  volumeName: {{ .Values.minio.volumeName }}
  {{- end }}
{{- end }}
