apiVersion: v2
name: sourcegraph-subchart
description: Customer-owned chart that inherits from Sourcegraph
type: application
version: "6.7.0"

dependencies:
- name: sourcegraph
  alias: sg # Optional, allows a custom name to be used
  version: "6.7.0"
  repository: "https://sourcegraph.github.io/deploy-sourcegraph-helm"
