{{- if and (not .Values.sourcegraph.disableKubernetesSecrets) (not .Values.redisCache.connection.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: redis-cache
    deploy: sourcegraph
    app.kubernetes.io/component: redis-cache
  name: {{ .Values.redisCache.name }}
type: Opaque
data:
  endpoint: {{ .Values.redisCache.connection.endpoint | toString | b64enc | quote }}
{{- end -}}
