{{- if .Values.redisCache.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.redisCache.serviceAnnotations }}
    {{- toYaml .Values.redisCache.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: redis-cache
    deploy: sourcegraph
    app.kubernetes.io/component: redis
    {{- if .Values.redisCache.serviceLabels }}
      {{- toYaml .Values.redisCache.serviceLabels | nindent 4 }}
    {{- end }}
  name: redis-cache
spec:
  ports:
  - name: http-metrics
    port: 9121
    targetPort: http-metrics
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "redisCache") | nindent 4 }}
    app: redis-cache
  type: {{ .Values.redisCache.serviceType | default "ClusterIP" }}
{{- end }}
