apiVersion: v2
name: sourcegraph-migrator
description: Chart for running Sourcegraph migrator
icon: https://sourcegraph.com/favicon.ico
type: application

# Chart version, separate from Sourcegraph
version: "3.43.1"

# Version of Sourcegraph release
appVersion: "3.43.1"
