apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.preciseCodeIntel.serviceAnnotations }}
    {{- toYaml .Values.preciseCodeIntel.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: precise-code-intel-worker
    deploy: sourcegraph
    app.kubernetes.io/component: precise-code-intel
    {{- if .Values.preciseCodeIntel.serviceLabels }}
      {{- toYaml .Values.preciseCodeIntel.serviceLabels | nindent 4 }}
    {{- end }}
  name: precise-code-intel-worker
spec:
  ports:
  - name: http
    port: 3188
    targetPort: http
  - name: http-debug
    port: 6060
    targetPort: http-debug
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "preciseCodeIntel") | nindent 4 }}
    app: precise-code-intel-worker
  type: {{ .Values.preciseCodeIntel.serviceType | default "ClusterIP" }}
