apiVersion: v2
name: sourcegraph-executor-dind
description: Chart for installing Sourcegraph executors using Docker in Docker (dind)
icon: https://sourcegraph.com/favicon.ico
type: application

# Chart version, separate from Sourcegraph
version: "5.10.0"

# Version of Sourcegraph release
appVersion: "5.10.0"
