apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Headless service that provides a stable network identity for the
      indexed-search stateful set.
    prometheus.io/port: "6070"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.indexedSearch.serviceAnnotations }}
    {{- toYaml .Values.indexedSearch.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: indexed-search
    deploy: sourcegraph
    app.kubernetes.io/component: indexed-search
    {{- if .Values.indexedSearch.serviceLabels }}
      {{- toYaml .Values.indexedSearch.serviceLabels | nindent 4 }}
    {{- end }}
  name: indexed-search
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 6070
    targetPort: grpc
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: indexed-search
  type: {{ .Values.indexedSearch.serviceType | default "ClusterIP" }}
