apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Headless service that provides a stable network identity for the indexed-search stateful set
    prometheus.io/port: "6072"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.indexedSearch.serviceAnnotations }}
    {{- toYaml .Values.indexedSearch.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "indexedSearch" "kind" "service" "componentLabel" "indexed-search") | nindent 4 }}
    app: indexed-search-indexer
  name: {{ default "indexed-search-indexer" .Values.indexedSearch.indexerName }}
spec:
  clusterIP: None
  ports:
  - name: grpc-indexer
    port: 6072
    targetPort: grpc-indexer
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "indexedSearch" "componentLabel" "indexed-search") | nindent 4 }}
    app: indexed-search
  type: {{ .Values.indexedSearch.serviceType | default "ClusterIP" }}
