{{- if .Values.codeIntelDB.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeIntelDB" "kind" "persistentvolumeclaim" "componentLabel" "codeintel-db") | nindent 4 }}
  name: {{ default "codeintel-db" .Values.codeIntelDB.name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.codeIntelDB.storageSize }}
  storageClassName: {{ .Values.storageClass.name }}
  {{- if .Values.codeIntelDB.volumeName }}
  volumeName: {{ .Values.codeIntelDB.volumeName }}
  {{- end }}
{{- end }}
