{{- if and .Values.codeIntelDB.enabled .Values.codeIntelDB.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeIntelDB" "kind" "serviceaccount" "componentLabel" "codeintel-db") | nindent 4 }}
  {{- include "sourcegraph.serviceAccountAnnotations" (list . "codeIntelDB") | trim | nindent 2 }}
  name: {{ include "sourcegraph.serviceAccountName" (list . "codeIntelDB") }}
{{- end }}
