{{- if .Values.codeIntelDB.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.codeIntelDB.serviceAnnotations }}
    {{- toYaml .Values.codeIntelDB.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeIntelDB" "kind" "service" "componentLabel" "codeintel-db") | nindent 4 }}
  name: codeintel-db
spec:
  ports:
  - name: http-metrics
    port: 9187
    targetPort: http-metrics
  - name: pgsql
    port: 5432
    targetPort: pgsql
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "codeIntelDB" "componentLabel" "codeintel-db") | nindent 4 }}
  type: {{ .Values.codeIntelDB.serviceType | default "ClusterIP" }}
{{- end }}
