{{- if .Values.codeIntelDB.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9187"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.codeIntelDB.serviceAnnotations }}
    {{- toYaml .Values.codeIntelDB.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/component: codeintel-db
    app: codeintel-db
    deploy: sourcegraph
    {{- if .Values.codeIntelDB.serviceLabels }}
      {{- toYaml .Values.codeIntelDB.serviceLabels | nindent 4 }}
    {{- end }}
  name: codeintel-db
spec:
  ports:
  - name: codeintel-db
    port: 5432
    targetPort: codeintel-db
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: codeintel-db
  type: {{ .Values.codeIntelDB.serviceType | default "ClusterIP" }}
{{- end }}
