{{- if and (not .Values.sourcegraph.disableKubernetesSecrets) (not .Values.codeIntelDB.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.codeIntelDB.name }}-auth
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "codeIntelDB" "kind" "secret" "componentLabel" "codeintel-db") | nindent 4 }}
type: Opaque
data:
  database: {{ .Values.codeIntelDB.auth.database | toString | b64enc | quote }}
  host: {{ .Values.codeIntelDB.auth.host | toString | b64enc | quote }}
  password: {{ .Values.codeIntelDB.auth.password | toString | b64enc | quote }}
  port: {{ .Values.codeIntelDB.auth.port | toString | b64enc | quote }}
  user: {{ .Values.codeIntelDB.auth.user | toString | b64enc | quote }}
  sslmode: {{ .Values.codeIntelDB.auth.sslmode | toString | b64enc | quote }}
{{- end -}}
