apiVersion: v2
name: sourcegraph
description: Chart for installing Sourcegraph
icon: https://sourcegraph.com/favicon.ico
type: application

# Chart version, separate from Sourcegraph
version: "5.6.185"

# Version of Sourcegraph release
appVersion: "5.6.185"
