apiVersion: v2
name: sourcegraph
description: Chart for installing Sourcegraph

type: application

# Chart version, separate from Sourcegraph
version: "3.40.2"

# Version of Sourcegraph release
appVersion: "3.40.2"
