apiVersion: v2
name: sourcegraph
description: Chart for installing Sourcegraph
icon: https://sourcegraph.com/favicon.ico
type: application

# Chart version, separate from Sourcegraph
version: "3.43.2"

# Version of Sourcegraph release
appVersion: "3.43.2"
