apiVersion: v2
name: sourcegraph
description: Chart for installing Sourcegraph
icon: https://sourcegraph.com/favicon.ico
type: application

# Chart version, separate from Sourcegraph
version: "6.1.5633"

# Version of Sourcegraph release
appVersion: "6.1.5633"
