apiVersion: v2
name: sourcegraph
description: Chart for installing Sourcegraph

type: application

# Chart version, separate from Sourcegraph
version: 1.0.0

# Version of Sourcegraph release
appVersion: "3.37.0"
