apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6996"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.worker.serviceAnnotations }}
    {{- toYaml .Values.worker.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: worker
    deploy: sourcegraph
    app.kubernetes.io/component: worker
    {{- if .Values.worker.serviceLabels }}
      {{- toYaml .Values.worker.serviceLabels | nindent 4 }}
    {{- end }}
  name: worker-executors
spec:
  ports:
  - name: http-debug-exec
    port: 6996
    targetPort: http-debug-exec
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "worker") | nindent 4 }}
    app: worker
  type: {{ .Values.worker.serviceType | default "ClusterIP" }}
