apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Headless service that provides a stable network identity for the
      gitserver stateful set.
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.gitserver.serviceAnnotations }}
    {{- toYaml .Values.gitserver.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "sourcegraph.labels" (dict "ctx" . "valuesKey" "gitserver" "kind" "service") | nindent 4 }}
    type: gitserver
  name: gitserver
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 3178
    targetPort: grpc
  - name: http-debug
    port: 6060
    targetPort: http-debug
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "gitserver") | nindent 4 }}
    type: gitserver
  type: {{ .Values.gitserver.serviceType | default "ClusterIP" }}
