{{- if .Values.jaeger.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- if .Values.jaeger.query.serviceAnnotations }}
  {{- toYaml .Values.jaeger.query.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
    deploy: sourcegraph
    app.kubernetes.io/component: all-in-one
    app: jaeger
    app.kubernetes.io/name: jaeger
    {{- if .Values.jaeger.query.serviceLabels }}
      {{- toYaml .Values.jaeger.query.serviceLabels | nindent 4 }}
    {{- end }}
  name: {{ default "jaeger-query" .Values.jaeger.query.name }}
spec:
  ports:
  - name: http
    port: 16686
    protocol: TCP
    targetPort: http
  selector:
    {{- include "sourcegraph.jaeger.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: all-in-one
    app: jaeger
  type: {{ .Values.jaeger.query.serviceType | default "ClusterIP" }}
{{- end }}
