apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Handles repository metadata (not Git data) lookups and updates from
      external code hosts and other similar services.
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    {{- if .Values.repoUpdater.labels }}
      {{- toYaml .Values.repoUpdater.labels | nindent 4 }}
    {{- end }}
    deploy: sourcegraph
    app.kubernetes.io/component: repo-updater
  name: {{ default "repo-updater" .Values.repoUpdater.name }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.repoUpdater.replicaCount }}
  revisionHistoryLimit: {{ .Values.sourcegraph.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "sourcegraph.selectorLabels" . | nindent 6 }}
      app: repo-updater
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: repo-updater
      {{- if .Values.sourcegraph.podAnnotations }}
      {{- toYaml .Values.sourcegraph.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.repoUpdater.podAnnotations }}
      {{- toYaml .Values.repoUpdater.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
      {{- include "sourcegraph.selectorLabels" . | nindent 8 }}
      {{- if .Values.sourcegraph.podLabels }}
      {{- toYaml .Values.sourcegraph.podLabels | nindent 8 }}
      {{- end }}
      {{- if .Values.repoUpdater.podLabels }}
      {{- toYaml .Values.repoUpdater.podLabels | nindent 8 }}
      {{- end }}
        deploy: sourcegraph
        app: repo-updater
    spec:
      containers:
      - name: repo-updater
        image: {{ include "sourcegraph.image" (list . "repoUpdater") }}
        imagePullPolicy: {{ .Values.sourcegraph.image.pullPolicy }}
        {{- with .Values.repoUpdater.args }}
        args:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        {{- range $name, $item := .Values.repoUpdater.env}}
        - name: {{ $name }}
          {{- $item | toYaml | nindent 10 }}
        {{- end }}
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - containerPort: 3182
          name: http
        - containerPort: 6060
          name: debug
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: debug
            scheme: HTTP
          periodSeconds: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: debug
            scheme: HTTP
          periodSeconds: 1
          timeoutSeconds: 5
        {{- if not .Values.sourcegraph.localDevMode }}
        resources:
          {{- toYaml .Values.repoUpdater.resources | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.repoUpdater.containerSecurityContext | nindent 10 }}
        volumeMounts:
        {{- if .Values.repoUpdater.extraVolumeMounts }}
        {{- toYaml .Values.repoUpdater.extraVolumeMounts | nindent 8 }}
        {{- end }}
      {{- include "sourcegraph.tracing" . | nindent 6 }}
      {{- if .Values.repoUpdater.extraContainers }}
        {{- toYaml .Values.repoUpdater.extraContainers | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.repoUpdater.podSecurityContext | nindent 8 }}
      {{- include "sourcegraph.nodeSelector" (list . "repoUpdater" ) | trim | nindent 6 }}
      {{- include "sourcegraph.affinity" (list . "repoUpdater" ) | trim | nindent 6 }}
      {{- include "sourcegraph.tolerations" (list . "repoUpdater" ) | trim | nindent 6 }}
      {{- with .Values.sourcegraph.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.repoUpdater.extraVolumes }}
      {{- toYaml .Values.repoUpdater.extraVolumes | nindent 6 }}
      {{- end }}
