apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "6060"
    sourcegraph.prometheus/scrape: "true"
    {{- if .Values.repoUpdater.serviceAnnotations }}
    {{- toYaml .Values.repoUpdater.serviceAnnotations | nindent 4 }}
    {{- end }}
  labels:
    app: repo-updater
    deploy: sourcegraph
    app.kubernetes.io/component: repo-updater
    {{- if .Values.repoUpdater.serviceLabels }}
      {{- toYaml .Values.repoUpdater.serviceLabels | nindent 4 }}
    {{- end }}
  name: {{ default "repo-updater" .Values.repoUpdater.name }}
spec:
  ports:
  - name: http
    port: 3182
    targetPort: http
  selector:
    {{- include "sourcegraph.selectorLabels" . | nindent 4 }}
    app: repo-updater
  type: {{ .Values.repoUpdater.serviceType | default "ClusterIP" }}
