{{- if and (not .Values.sourcegraph.disableKubernetesSecrets) (not .Values.redisStore.connection.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redisStore.name }}
  labels:
    app: redis-store
    deploy: sourcegraph
    app.kubernetes.io/component: redis-store
type: Opaque
data:
  endpoint: {{ .Values.redisStore.connection.endpoint | toString | b64enc | quote }}
{{- end -}}
