{{- if .Values.private-docker-registry.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.private-docker-registry.serviceAnnotations }}
    annotations:
    {{- toYaml .Values.private-docker-registry.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
    app: private-docker-registry
    deploy: sourcegraph
    app.kubernetes.io/component: private-docker-registry
  name: private-docker-registry
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: private-docker-registry
  type: ClusterIP
{{- end }}
