{{- if and .Values.prometheus.enabled .Values.prometheus.privileged .Values.prometheus.createRoleBinding -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    category: rbac
    deploy: sourcegraph
    app.kubernetes.io/component: prometheus
  name: {{ .Values.prometheus.name }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: {{ .Values.prometheus.name }}
subjects:
- name: {{ include "sourcegraph.serviceAccountName" (list . "prometheus") }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
{{- end }}
