{{- if .Values.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.prometheus.serviceAnnotations }}
  annotations:
    {{- toYaml .Values.prometheus.serviceAnnotations | nindent 4 }}
  {{- end }}
  labels:
    app: prometheus
    deploy: sourcegraph
    app.kubernetes.io/component: prometheus
    {{- if .Values.prometheus.serviceLabels }}
      {{- toYaml .Values.prometheus.serviceLabels | nindent 4 }}
    {{- end }}
  name: prometheus
spec:
  ports:
  - name: http
    port: 30090
    targetPort: http
  selector:
    {{- include "sourcegraph.selectorLabels" (dict "ctx" . "valuesKey" "prometheus") | nindent 4 }}
    app: prometheus
  type: {{ .Values.prometheus.serviceType | default "ClusterIP" }}
{{- end }}
